// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgID.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from MsgID.proto</summary>
  public static partial class MsgIDReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtNc2dJRC5wcm90bxIIUHJvdG9jb2wqggEKBU1zZ0lEEgwKCExvZ2luUmVx",
            "EAASDAoITG9naW5Sc3AQARIPCgtMb2dpbk91dFJlcRACEg8KC0xvZ2luT3V0",
            "UnNwEAMSFAoQU3RlZXJQb3NpdGlvblJlcRAEEhQKEFN0ZWVyUG9zaXRpb25S",
            "c3AQBRIPCgtMb2NrU3RlcEVuZBAGYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MsgID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgID {
    [pbr::OriginalName("LoginReq")] LoginReq = 0,
    [pbr::OriginalName("LoginRsp")] LoginRsp = 1,
    [pbr::OriginalName("LoginOutReq")] LoginOutReq = 2,
    [pbr::OriginalName("LoginOutRsp")] LoginOutRsp = 3,
    [pbr::OriginalName("SteerPositionReq")] SteerPositionReq = 4,
    [pbr::OriginalName("SteerPositionRsp")] SteerPositionRsp = 5,
    [pbr::OriginalName("LockStepEnd")] LockStepEnd = 6,
  }

  #endregion

}

#endregion Designer generated code
